import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/Header/Header";
import { NextAuthProvider } from "@/components/providers/NextAuthProvider";

const inter = Poppins({
  weight: ["400", "600", "800", "700"],
  subsets: ["devanagari"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  min-h-screen min-w-full bg-neutral-900 flex flex-col`}
      >
        <NextAuthProvider>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
