import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Header } from "@/components/ui/Header/Header";
import { Providers } from "@/components/providers/Providers";
import { Theme } from "@radix-ui/themes";

const inter = Poppins({
  weight: ["400", "600", "800", "700"],
  subsets: ["devanagari"],
});

export const metadata: Metadata = {
  title: "PollPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  flex min-h-screen w-full min-w-[95vw] flex-col bg-neutral-900`}
      >
        <Providers>
          <Theme accentColor="orange" panelBackground="solid" appearance="dark">
            <Header />
            {children}
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
